#pragma once

#define HEADER_NAME_LEN 256
#define HEADER_VALUE_LEN 4096
#define REQUEST_PATH_MAX_LENGTH 4096
#define QUERY_STRING_MAX_LENGTH 40960
#define HTTP_METHOD_MAX_LENGTH 5
#define HTTP_VERSION_STR_MAX_LENGTH 9
#define TCP_BACKLOG_SIZE 5
#define DEFAULT_HTTP_VERSION_STR "HTTP/1.0"
